/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_unihalle_informatik_MiToBo_core_datatypes_Polygon2D_Cgal */

#ifndef _Included_de_unihalle_informatik_MiToBo_core_datatypes_Polygon2D_Cgal
#define _Included_de_unihalle_informatik_MiToBo_core_datatypes_Polygon2D_Cgal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_unihalle_informatik_MiToBo_core_datatypes_Polygon2D_Cgal
 * Method:    cgal_isSimple
 * Signature: ([D[D)Z
 */
JNIEXPORT jboolean JNICALL Java_de_unihalle_informatik_MiToBo_core_datatypes_Polygon2D_1Cgal_cgal_1isSimple
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray);

/*
 * Class:     de_unihalle_informatik_MiToBo_core_datatypes_Polygon2D_Cgal
 * Method:    cgal_isConvex
 * Signature: ([D[D)Z
 */
JNIEXPORT jboolean JNICALL Java_de_unihalle_informatik_MiToBo_core_datatypes_Polygon2D_1Cgal_cgal_1isConvex
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray);

/*
 * Class:     de_unihalle_informatik_MiToBo_core_datatypes_Polygon2D_Cgal
 * Method:    cgal_orientation
 * Signature: ([D[D[D)I
 */
JNIEXPORT jint JNICALL Java_de_unihalle_informatik_MiToBo_core_datatypes_Polygon2D_1Cgal_cgal_1orientation
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     de_unihalle_informatik_MiToBo_core_datatypes_Polygon2D_Cgal
 * Method:    cgal_isCounterclockwiseOriented
 * Signature: ([D[D)Z
 */
JNIEXPORT jboolean JNICALL Java_de_unihalle_informatik_MiToBo_core_datatypes_Polygon2D_1Cgal_cgal_1isCounterclockwiseOriented
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray);

/*
 * Class:     de_unihalle_informatik_MiToBo_core_datatypes_Polygon2D_Cgal
 * Method:    cgal_isClockwiseOriented
 * Signature: ([D[D)Z
 */
JNIEXPORT jboolean JNICALL Java_de_unihalle_informatik_MiToBo_core_datatypes_Polygon2D_1Cgal_cgal_1isClockwiseOriented
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray);

/*
 * Class:     de_unihalle_informatik_MiToBo_core_datatypes_Polygon2D_Cgal
 * Method:    cgal_signedArea
 * Signature: ([D[D)D
 */
JNIEXPORT jdouble JNICALL Java_de_unihalle_informatik_MiToBo_core_datatypes_Polygon2D_1Cgal_cgal_1signedArea
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray);

/*
 * Class:     de_unihalle_informatik_MiToBo_core_datatypes_Polygon2D_Cgal
 * Method:    cgal_makePolySimple
 * Signature: ([D[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_de_unihalle_informatik_MiToBo_core_datatypes_Polygon2D_1Cgal_cgal_1makePolySimple
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
